services:
  db:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=my-nestjs-practice
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_ROOT_PASSWORD=rootuser
    ports:
      - "3307:3306"